<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/kint/Kint.class.php';

function custom_example_menu() {
    $items['Field'] = array(
        'page callback' => 'field',
        'access arguments' => array(
            'access my_module via ajax'
        ),
        'type' => MENU_CALLBACK
    );
    
    drupal_add_js(drupal_get_path("module", "custom_example") . "/custom_example.js");
    return $items;
}




function field() {
    
    $field = $_REQUEST["field"];
    $node  = node_load($_REQUEST["nid"]);
    
    if (empty($_REQUEST["value"])) {
        $value = field_get_items('node', $node, $_REQUEST["field"]);
        print($value[0]["value"]);
        exit();
    } else {
        if (node_access('update', $node)) {
            $node->{$_REQUEST["field"]}['und'][0]["value"] = $_REQUEST["value"];
            node_save($node);
            print t('');
            exit();
        }
    }
}